insert into cities (id, name, slug, state, active, car_count, inspection_centers, avg_price_lakh, lat, lng)
values
  ('00000000-0000-0000-0000-000000000001', 'Mumbai', 'mumbai', 'Maharashtra', true, 2842, 4, 12.80, 19.076000, 72.877700),
  ('00000000-0000-0000-0000-000000000002', 'Delhi', 'delhi', 'NCR', true, 3214, 5, 13.40, 28.704100, 77.102500),
  ('00000000-0000-0000-0000-000000000003', 'Bengaluru', 'bengaluru', 'Karnataka', true, 2687, 4, 14.10, 12.971600, 77.594600),
  ('00000000-0000-0000-0000-000000000004', 'Pune', 'pune', 'Maharashtra', true, 1842, 3, 12.20, 18.520400, 73.856700)
on conflict (slug) do nothing;

-- Password for demo users is demo1234. Replace with bcrypt hashes generated by the API seed script in production.
insert into users (id, name, email, phone, password_hash, role, kyc_status, city_id, is_verified)
values
  ('10000000-0000-0000-0000-000000000001', 'Arjun Sharma', 'arjun.sharma@email.com', '+919876543210', '$2a$10$1kmbnRjZSWQ76e9H1r5dS.YzTVi54F7FqDvwcBSvxzFTo95Ofz3zC', 'buyer', 'approved', '00000000-0000-0000-0000-000000000001', true),
  ('10000000-0000-0000-0000-000000000002', 'Priya Nair', 'priya.nair@email.com', '+919876543211', '$2a$10$1kmbnRjZSWQ76e9H1r5dS.YzTVi54F7FqDvwcBSvxzFTo95Ofz3zC', 'seller', 'approved', '00000000-0000-0000-0000-000000000003', true),
  ('10000000-0000-0000-0000-000000000003', 'Admin User', 'admin@trustedcars.in', '+919876543212', '$2a$10$1kmbnRjZSWQ76e9H1r5dS.YzTVi54F7FqDvwcBSvxzFTo95Ofz3zC', 'admin', 'approved', '00000000-0000-0000-0000-000000000003', true)
on conflict (phone) do nothing;

insert into cars (id, seller_id, city_id, make, model, variant, year, price_paise, km_driven, fuel_type, transmission, owner_count, body_type, color, registration_number, status, quality_score, fraud_score, description, primary_image_url)
values
  ('20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000003', 'Hyundai', 'Creta', 'SX(O) 1.5 Diesel AT', 2022, 164500000, 18420, 'Diesel', 'Automatic', 1, 'SUV', 'Phantom Black', 'KA03TC2022', 'active', 94, 8, 'Top-spec Creta with sunroof, ventilated seats, Bose audio and full service history.', 'https://images.pexels.com/photos/31040132/pexels-photo-31040132.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1200'),
  ('20000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Maruti Suzuki', 'Swift', 'ZXi+ AMT', 2023, 78500000, 9120, 'Petrol', 'Automatic', 1, 'Hatchback', 'Pearl White', 'MH02TC2023', 'active', 96, 4, 'Almost-new Swift ZXi+ with clean service history.', 'https://images.pexels.com/photos/33686091/pexels-photo-33686091.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1200')
on conflict (registration_number) do nothing;

insert into inspections (id, car_id, inspector_id, status, scheduled_at, completed_at, score, summary, share_token)
values
  ('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000003', 'completed', now(), now(), 94, 'Passed TrustedCars certification with a 94/100 score.', 'share_creta_2022')
on conflict (share_token) do nothing;