"""add_mfa_backup_codes

Revision ID: 305bf79be658
Revises: 8f4f152cfb85
Create Date: 2026-06-18 07:09:32.961157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305bf79be658'
down_revision: Union[str, None] = '8f4f152cfb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_mfa_backup_codes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('code_hash', sa.String(length=255), nullable=False),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'code_hash', name='uq_mfa_backup_user_code_hash'),
    )
    op.create_index(
        'ix_user_mfa_backup_codes_user_id',
        'user_mfa_backup_codes',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_user_mfa_backup_codes_user_id',
        table_name='user_mfa_backup_codes',
    )
    op.drop_table('user_mfa_backup_codes')
    # ### end Alembic commands ###
