"""admin_hardening_v2

Revision ID: 397d0979ac67
Revises: 3c7c35800388
Create Date: 2026-06-18 07:47:25.165131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397d0979ac67'
down_revision: Union[str, None] = '305bf79be658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE deleted_reason_enum ADD VALUE IF NOT EXISTS 'spam'")
    op.execute("ALTER TYPE deleted_reason_enum ADD VALUE IF NOT EXISTS 'fraud'")

    op.add_column('audit_logs', sa.Column('target_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.add_column('cars', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_cars_is_featured'), 'cars', ['is_featured'], unique=False)
    op.add_column('dealerships', sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_dealerships_is_suspended'), 'dealerships', ['is_suspended'], unique=False)
    op.add_column('inquiries', sa.Column('previous_status', sa.Enum('open', 'closed', 'archived', name='inquiry_status_enum'), nullable=True))
    op.add_column('outbox_events', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_outbox_events_idempotency_key'), 'outbox_events', ['idempotency_key'], unique=True)
    op.add_column('platform_statistics', sa.Column('suspended_dealers', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_users_is_suspended'), 'users', ['is_suspended'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_suspended'), table_name='users')
    op.drop_column('users', 'is_suspended')
    op.drop_column('platform_statistics', 'suspended_dealers')
    op.drop_index(op.f('ix_outbox_events_idempotency_key'), table_name='outbox_events')
    op.drop_column('outbox_events', 'idempotency_key')
    op.drop_column('inquiries', 'previous_status')
    op.drop_index(op.f('ix_dealerships_is_suspended'), table_name='dealerships')
    op.drop_column('dealerships', 'is_suspended')
    op.drop_index(op.f('ix_cars_is_featured'), table_name='cars')
    op.drop_column('cars', 'is_featured')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'target_id')
    # ### end Alembic commands ###
