"""wishlist performance index

Revision ID: 3acbf5ef46f4
Revises: 877df017d457
Create Date: 2026-06-18 01:32:24.201315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acbf5ef46f4'
down_revision: Union[str, None] = '877df017d457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wishlist_user_deleted_created', 'wishlist', ['user_id', 'deleted_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_user_deleted_created', table_name='wishlist')
    # ### end Alembic commands ###
