"""inquiries fixes

Revision ID: 3b525e9fc3e8
Revises: ebe8bf58e03d
Create Date: 2026-06-18 01:24:57.805102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b525e9fc3e8'
down_revision: Union[str, None] = 'ebe8bf58e03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_inquiries_one_per_car_buyer', 'inquiries', ['car_id', 'buyer_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_inquiry_messages_created', 'inquiry_messages', ['created_at'], unique=False)
    op.create_index('ix_inquiry_messages_inquiry_created', 'inquiry_messages', ['inquiry_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inquiry_messages_inquiry_created', table_name='inquiry_messages')
    op.drop_index('ix_inquiry_messages_created', table_name='inquiry_messages')
    op.drop_index('idx_inquiries_one_per_car_buyer', table_name='inquiries', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
