"""add wishlist module

Revision ID: 877df017d457
Revises: 3b525e9fc3e8
Create Date: 2026-06-18 01:28:00.871412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877df017d457'
down_revision: Union[str, None] = '3b525e9fc3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wishlist_unique_user_car', 'wishlist', ['user_id', 'car_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_wishlist_car_id', 'wishlist', ['car_id'], unique=False)
    op.create_index('ix_wishlist_user_id', 'wishlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_user_id', table_name='wishlist')
    op.drop_index('ix_wishlist_car_id', table_name='wishlist')
    op.drop_index('idx_wishlist_unique_user_car', table_name='wishlist', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('wishlist')
    # ### end Alembic commands ###
