"""Add audit log composite indexes

Revision ID: 8c01a0f55161
Revises: 397d0979ac67
Create Date: 2026-06-18 15:53:31.608478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c01a0f55161'
down_revision: Union[str, None] = '397d0979ac67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at', 'id'], unique=False)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_audit_logs_corr_created', 'audit_logs', ['correlation_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_audit_logs_created_id', 'audit_logs', ['created_at', 'id'], unique=False)
    op.create_index('ix_audit_logs_target_created', 'audit_logs', ['target_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_target_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_corr_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    # ### end Alembic commands ###
