"""reviews optimization

Revision ID: c4fc45662288
Revises: fc7151256045
Create Date: 2026-06-18 01:48:09.742497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fc45662288'
down_revision: Union[str, None] = 'fc7151256045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reviews_seller_deleted_created', 'reviews', ['seller_id', 'deleted_at', sa.text('created_at DESC')], unique=False)
    op.drop_index('idx_reviews_one_per_reviewer_seller_car', table_name='reviews', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_reviews_one_per_reviewer_seller_car', 'reviews', ['reviewer_id', 'seller_id', 'car_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_one_per_reviewer_seller_car', table_name='reviews')
    op.create_index('idx_reviews_one_per_reviewer_seller_car', 'reviews', ['reviewer_id', 'seller_id', 'car_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_reviews_seller_deleted_created', table_name='reviews')
    # ### end Alembic commands ###
