"""pre_admin_hardening_final

Revision ID: d1653e8c5fff
Revises: c4fc45662288
Create Date: 2026-06-18 04:39:42.906238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1653e8c5fff'
down_revision: Union[str, None] = 'c4fc45662288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', name='outboxeventstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_causation_id'), 'outbox_events', ['causation_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_correlation_id'), 'outbox_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index('ix_outbox_events_status_last_attempt_at', 'outbox_events', ['status', 'last_attempt_at'], unique=False)
    op.create_index('ix_outbox_events_status_next_retry_at', 'outbox_events', ['status', 'next_retry_at'], unique=False)
    op.create_table('platform_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('suspended_users', sa.Integer(), nullable=False),
    sa.Column('total_dealers', sa.Integer(), nullable=False),
    sa.Column('active_dealers', sa.Integer(), nullable=False),
    sa.Column('pending_cars', sa.Integer(), nullable=False),
    sa.Column('active_cars', sa.Integer(), nullable=False),
    sa.Column('hidden_cars', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('total_inquiries', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('correlation_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('request_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.execute("CREATE TYPE deleted_reason_enum AS ENUM ('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation')")
    op.add_column('car_images', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('car_images', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('cars', sa.Column('moderation_status', sa.String(length=50), nullable=True))
    op.add_column('cars', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cars', sa.Column('moderated_by', sa.UUID(), nullable=True))
    op.add_column('cars', sa.Column('moderation_reason', sa.Text(), nullable=True))
    op.add_column('cars', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('cars', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cars_moderation_status'), 'cars', ['moderation_status'], unique=False)
    op.create_index('ix_cars_user_id', 'cars', ['user_id'], unique=False)
    op.add_column('dealerships', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dealerships', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('dealerships', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('inquiries', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('inquiries', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index('ix_inquiries_buyer_del_upd', 'inquiries', ['buyer_id', 'deleted_at', sa.text('updated_at DESC')], unique=False)
    op.create_index('ix_inquiries_seller_del_upd', 'inquiries', ['seller_id', 'deleted_at', sa.text('updated_at DESC')], unique=False)
    op.add_column('inquiry_messages', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('inquiry_messages', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('reviews', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_key_version', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('mfa_backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('wishlist', sa.Column('deleted_reason', sa.Enum('user_request', 'admin_action', 'account_deleted', 'car_deleted', 'policy_violation', name='deleted_reason_enum'), nullable=True))
    op.add_column('wishlist', sa.Column('deleted_by', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'deleted_by')
    op.drop_column('wishlist', 'deleted_reason')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_reason')
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'mfa_key_version')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('reviews', 'deleted_by')
    op.drop_column('reviews', 'deleted_reason')
    op.drop_column('inquiry_messages', 'deleted_by')
    op.drop_column('inquiry_messages', 'deleted_reason')
    op.drop_index('ix_inquiries_seller_del_upd', table_name='inquiries')
    op.drop_index('ix_inquiries_buyer_del_upd', table_name='inquiries')
    op.drop_column('inquiries', 'deleted_by')
    op.drop_column('inquiries', 'deleted_reason')
    op.drop_column('dealerships', 'deleted_by')
    op.drop_column('dealerships', 'deleted_reason')
    op.drop_column('dealerships', 'deleted_at')
    op.drop_index('ix_cars_user_id', table_name='cars')
    op.drop_index(op.f('ix_cars_moderation_status'), table_name='cars')
    op.drop_column('cars', 'deleted_by')
    op.drop_column('cars', 'deleted_reason')
    op.drop_column('cars', 'moderation_reason')
    op.drop_column('cars', 'moderated_by')
    op.drop_column('cars', 'moderated_at')
    op.drop_column('cars', 'moderation_status')
    op.drop_column('car_images', 'deleted_by')
    op.drop_column('car_images', 'deleted_reason')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_table('platform_statistics')
    op.drop_index('ix_outbox_events_status_next_retry_at', table_name='outbox_events')
    op.drop_index('ix_outbox_events_status_last_attempt_at', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_correlation_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_causation_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.execute("DROP TYPE deleted_reason_enum")
    # ### end Alembic commands ###
