"""cars module

Revision ID: e49a30202d8f
Revises: 09867216f620
Create Date: 2026-06-17 19:47:05.229516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49a30202d8f'
down_revision: Union[str, None] = '09867216f620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dealership_id', sa.UUID(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('transmission', sa.String(length=50), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('ownership_count', sa.Integer(), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quality_grade', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'sold', 'rejected', name='car_status_enum'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_asking_price'), 'cars', ['asking_price'], unique=False)
    op.create_index(op.f('ix_cars_city'), 'cars', ['city'], unique=False)
    op.create_index(op.f('ix_cars_deleted_at'), 'cars', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cars_fuel_type'), 'cars', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_cars_make'), 'cars', ['make'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_state'), 'cars', ['state'], unique=False)
    op.create_index(op.f('ix_cars_status'), 'cars', ['status'], unique=False)
    op.create_index(op.f('ix_cars_transmission'), 'cars', ['transmission'], unique=False)
    op.create_index(op.f('ix_cars_year'), 'cars', ['year'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_cars_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_transmission'), table_name='cars')
    op.drop_index(op.f('ix_cars_status'), table_name='cars')
    op.drop_index(op.f('ix_cars_state'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_make'), table_name='cars')
    op.drop_index(op.f('ix_cars_fuel_type'), table_name='cars')
    op.drop_index(op.f('ix_cars_deleted_at'), table_name='cars')
    op.drop_index(op.f('ix_cars_city'), table_name='cars')
    op.drop_index(op.f('ix_cars_asking_price'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
