"""add_previous_moderation_status

Revision ID: ea5c7ec6df31
Revises: d1653e8c5fff
Create Date: 2026-06-18 05:12:10.345416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5c7ec6df31'
down_revision: Union[str, None] = 'd1653e8c5fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
