"""recovery migration

Revision ID: ebe8bf58e03d
Revises: eeabc673a01f
Create Date: 2026-06-17 20:21:57.849081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe8bf58e03d'
down_revision: Union[str, None] = 'eeabc673a01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'archived', name='inquiry_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inquiries_buyer', 'inquiries', ['buyer_id'], unique=False)
    op.create_index('ix_inquiries_car', 'inquiries', ['car_id'], unique=False)
    op.create_index('ix_inquiries_seller', 'inquiries', ['seller_id'], unique=False)
    op.create_index('ix_inquiries_status', 'inquiries', ['status'], unique=False)
    op.create_table('inquiry_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiry_messages_inquiry_id'), 'inquiry_messages', ['inquiry_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_car_images_active', 'car_images', ['car_id', 'deleted_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_car_images_one_primary', 'car_images', ['car_id'], unique=True, postgresql_where='is_primary = true AND deleted_at IS NULL')
    op.create_index(op.f('ix_car_images_car_id'), 'car_images', ['car_id'], unique=False)
    op.create_index(op.f('ix_car_images_storage_key'), 'car_images', ['storage_key'], unique=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_car_images_storage_key'), table_name='car_images')
    op.drop_index(op.f('ix_car_images_car_id'), table_name='car_images')
    op.drop_index('idx_car_images_one_primary', table_name='car_images', postgresql_where='is_primary = true AND deleted_at IS NULL')
    op.drop_index('idx_car_images_active', table_name='car_images', postgresql_where='deleted_at IS NULL')
    op.drop_table('car_images')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_inquiry_messages_inquiry_id'), table_name='inquiry_messages')
    op.drop_table('inquiry_messages')
    op.drop_index('ix_inquiries_status', table_name='inquiries')
    op.drop_index('ix_inquiries_seller', table_name='inquiries')
    op.drop_index('ix_inquiries_car', table_name='inquiries')
    op.drop_index('ix_inquiries_buyer', table_name='inquiries')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
