"""add reviews module

Revision ID: fc7151256045
Revises: 3acbf5ef46f4
Create Date: 2026-06-18 01:38:16.614962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7151256045'
down_revision: Union[str, None] = '3acbf5ef46f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_one_per_reviewer_seller_car', 'reviews', ['reviewer_id', 'seller_id', 'car_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_reviews_car_id', 'reviews', ['car_id'], unique=False)
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_reviewer_id', 'reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_reviews_seller_id', 'reviews', ['seller_id'], unique=False)
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('review_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'review_count')
    op.drop_column('users', 'rating')
    op.drop_index('ix_reviews_seller_id', table_name='reviews')
    op.drop_index('ix_reviews_reviewer_id', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_index('ix_reviews_car_id', table_name='reviews')
    op.drop_index('idx_reviews_one_per_reviewer_seller_car', table_name='reviews', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('reviews')
    # ### end Alembic commands ###
