import enum


class PermissionEnum(str, enum.Enum):
    VIEW_ADMIN_DASHBOARD = "VIEW_ADMIN_DASHBOARD"
    SUSPEND_USER = "SUSPEND_USER"
    RESTORE_USER = "RESTORE_USER"
    DELETE_USER = "DELETE_USER"

    SUSPEND_DEALER = "SUSPEND_DEALER"
    RESTORE_DEALER = "RESTORE_DEALER"
    DELETE_DEALER = "DELETE_DEALER"

    APPROVE_CAR = "APPROVE_CAR"
    REJECT_CAR = "REJECT_CAR"
    HIDE_CAR = "HIDE_CAR"
    RESTORE_CAR = "RESTORE_CAR"
    FEATURE_CAR = "FEATURE_CAR"

    DELETE_REVIEW = "DELETE_REVIEW"
    RESTORE_REVIEW = "RESTORE_REVIEW"

    CLOSE_INQUIRY = "CLOSE_INQUIRY"
    ARCHIVE_INQUIRY = "ARCHIVE_INQUIRY"
    REOPEN_INQUIRY = "REOPEN_INQUIRY"
    DELETE_INQUIRY = "DELETE_INQUIRY"

    VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS"

    MODERATE_ANY = "MODERATE_ANY"
    MANAGE_SETTINGS = "MANAGE_SETTINGS"
